// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CommandResponseStatus.
const (
	BadRequest     CommandResponseStatus = "bad_request"
	InternalError  CommandResponseStatus = "internal_error"
	InvalidRequest CommandResponseStatus = "invalid_request"
	NotInRoom      CommandResponseStatus = "not_in_room"
	Ok             CommandResponseStatus = "ok"
	RoomExists     CommandResponseStatus = "room_exists"
	RoomFull       CommandResponseStatus = "room_full"
	RoomNotFound   CommandResponseStatus = "room_not_found"
	Unauthorized   CommandResponseStatus = "unauthorized"
)

// Valid indicates whether the value is a known member of the CommandResponseStatus enum.
func (e CommandResponseStatus) Valid() bool {
	switch e {
	case BadRequest:
		return true
	case InternalError:
		return true
	case InvalidRequest:
		return true
	case NotInRoom:
		return true
	case Ok:
		return true
	case RoomExists:
		return true
	case RoomFull:
		return true
	case RoomNotFound:
		return true
	case Unauthorized:
		return true
	default:
		return false
	}
}

// Defines values for RoomEventCmd.
const (
	Chat       RoomEventCmd = "chat"
	UserJoined RoomEventCmd = "user_joined"
	UserLeft   RoomEventCmd = "user_left"
)

// Valid indicates whether the value is a known member of the RoomEventCmd enum.
func (e RoomEventCmd) Valid() bool {
	switch e {
	case Chat:
		return true
	case UserJoined:
		return true
	case UserLeft:
		return true
	default:
		return false
	}
}

// AuthRequest defines model for AuthRequest.
type AuthRequest struct {
	Cmd interface{} `json:"cmd"`

	// RID Opaque client-provided request correlation identifier.
	RID  RequestID `json:"rID"`
	User string    `json:"user"`
}

// ChatRequest defines model for ChatRequest.
type ChatRequest struct {
	Cmd     interface{} `json:"cmd"`
	Message string      `json:"message"`

	// RID Opaque client-provided request correlation identifier.
	RID RequestID `json:"rID"`
}

// CommandResponse defines model for CommandResponse.
type CommandResponse struct {
	Cmd string `json:"cmd"`

	// RID Opaque client-provided request correlation identifier.
	RID    RequestID             `json:"rID"`
	Status CommandResponseStatus `json:"status"`
}

// CommandResponseStatus defines model for CommandResponse.Status.
type CommandResponseStatus string

// CreateAndJoinRoomRequest defines model for CreateAndJoinRoomRequest.
type CreateAndJoinRoomRequest struct {
	Cmd  interface{} `json:"cmd"`
	Name string      `json:"name"`

	// RID Opaque client-provided request correlation identifier.
	RID RequestID `json:"rID"`
}

// JoinRoomRequest defines model for JoinRoomRequest.
type JoinRoomRequest struct {
	Cmd  interface{} `json:"cmd"`
	Name string      `json:"name"`

	// RID Opaque client-provided request correlation identifier.
	RID RequestID `json:"rID"`
}

// LeaveRoomRequest defines model for LeaveRoomRequest.
type LeaveRoomRequest struct {
	Cmd  interface{} `json:"cmd"`
	Name *string     `json:"name,omitempty"`

	// RID Opaque client-provided request correlation identifier.
	RID RequestID `json:"rID"`
}

// RequestID Opaque client-provided request correlation identifier.
type RequestID struct {
	union json.RawMessage
}

// RequestID0 defines model for RequestID.0.
type RequestID0 = string

// RequestID1 defines model for RequestID.1.
type RequestID1 = int

// RoomEvent defines model for RoomEvent.
type RoomEvent struct {
	Cmd     RoomEventCmd `json:"cmd"`
	Message *string      `json:"message,omitempty"`
	User    string       `json:"user"`
}

// RoomEventCmd defines model for RoomEvent.Cmd.
type RoomEventCmd string

// AsRequestID0 returns the union data inside the RequestID as a RequestID0
func (t RequestID) AsRequestID0() (RequestID0, error) {
	var body RequestID0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRequestID0 overwrites any union data inside the RequestID as the provided RequestID0
func (t *RequestID) FromRequestID0(v RequestID0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRequestID0 performs a merge with any union data inside the RequestID, using the provided RequestID0
func (t *RequestID) MergeRequestID0(v RequestID0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRequestID1 returns the union data inside the RequestID as a RequestID1
func (t RequestID) AsRequestID1() (RequestID1, error) {
	var body RequestID1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRequestID1 overwrites any union data inside the RequestID as the provided RequestID1
func (t *RequestID) FromRequestID1(v RequestID1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRequestID1 performs a merge with any union data inside the RequestID, using the provided RequestID1
func (t *RequestID) MergeRequestID1(v RequestID1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RequestID) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RequestID) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /healthz)
	Healthcheck(w http.ResponseWriter, r *http.Request)
	// GetWs WebSocket chat endpoint
	// (GET /ws)
	GetWs(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Healthcheck operation middleware
func (siw *ServerInterfaceWrapper) Healthcheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthcheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWs operation middleware
func (siw *ServerInterfaceWrapper) GetWs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/healthz", wrapper.Healthcheck).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/ws", wrapper.GetWs).Methods(http.MethodGet)

	return r
}

type HealthcheckRequestObject struct {
}

type HealthcheckResponseObject interface {
	VisitHealthcheckResponse(w http.ResponseWriter) error
}

type Healthcheck200TextResponse string

func (response Healthcheck200TextResponse) VisitHealthcheckResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(fmt.Sprint(response)))
	return err
}

type GetWsRequestObject struct {
}

type GetWsResponseObject interface {
	VisitGetWsResponse(w http.ResponseWriter) error
}

type GetWs101Response struct {
}

func (response GetWs101Response) VisitGetWsResponse(w http.ResponseWriter) error {
	w.WriteHeader(101)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /healthz)
	Healthcheck(ctx context.Context, request HealthcheckRequestObject) (HealthcheckResponseObject, error)
	// GetWs WebSocket chat endpoint
	// (GET /ws)
	GetWs(ctx context.Context, request GetWsRequestObject) (GetWsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Healthcheck operation middleware
func (sh *strictHandler) Healthcheck(w http.ResponseWriter, r *http.Request) {
	var request HealthcheckRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Healthcheck(ctx, request.(HealthcheckRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthcheck")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthcheckResponseObject); ok {
		if err := validResponse.VisitHealthcheckResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWs operation middleware
func (sh *strictHandler) GetWs(w http.ResponseWriter, r *http.Request) {
	var request GetWsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWs(ctx, request.(GetWsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWsResponseObject); ok {
		if err := validResponse.VisitGetWsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
