// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	"github.com/Dragonqos/lockwood-test/internal/resources/chat/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateAndJoin provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateAndJoin(ctx context.Context, room domain.Room, membership domain.Membership) error {
	ret := _mock.Called(ctx, room, membership)

	if len(ret) == 0 {
		panic("no return value specified for CreateAndJoin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Room, domain.Membership) error); ok {
		r0 = returnFunc(ctx, room, membership)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateAndJoin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAndJoin'
type MockRepository_CreateAndJoin_Call struct {
	*mock.Call
}

// CreateAndJoin is a helper method to define mock.On call
//   - ctx context.Context
//   - room domain.Room
//   - membership domain.Membership
func (_e *MockRepository_Expecter) CreateAndJoin(ctx any, room any, membership any) *MockRepository_CreateAndJoin_Call {
	return &MockRepository_CreateAndJoin_Call{Call: _e.mock.On("CreateAndJoin", ctx, room, membership)}
}

func (_c *MockRepository_CreateAndJoin_Call) Run(run func(ctx context.Context, room domain.Room, membership domain.Membership)) *MockRepository_CreateAndJoin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Room
		if args[1] != nil {
			arg1 = args[1].(domain.Room)
		}
		var arg2 domain.Membership
		if args[2] != nil {
			arg2 = args[2].(domain.Membership)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_CreateAndJoin_Call) Return(err error) *MockRepository_CreateAndJoin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateAndJoin_Call) RunAndReturn(run func(ctx context.Context, room domain.Room, membership domain.Membership) error) *MockRepository_CreateAndJoin_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentRoom provides a mock function for the type MockRepository
func (_mock *MockRepository) CurrentRoom(ctx context.Context, userID string) (domain.RoomID, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CurrentRoom")
	}

	var r0 domain.RoomID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.RoomID, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.RoomID); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.RoomID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CurrentRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentRoom'
type MockRepository_CurrentRoom_Call struct {
	*mock.Call
}

// CurrentRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) CurrentRoom(ctx any, userID any) *MockRepository_CurrentRoom_Call {
	return &MockRepository_CurrentRoom_Call{Call: _e.mock.On("CurrentRoom", ctx, userID)}
}

func (_c *MockRepository_CurrentRoom_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_CurrentRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CurrentRoom_Call) Return(roomID domain.RoomID, err error) *MockRepository_CurrentRoom_Call {
	_c.Call.Return(roomID, err)
	return _c
}

func (_c *MockRepository_CurrentRoom_Call) RunAndReturn(run func(ctx context.Context, userID string) (domain.RoomID, error)) *MockRepository_CurrentRoom_Call {
	_c.Call.Return(run)
	return _c
}

// Join provides a mock function for the type MockRepository
func (_mock *MockRepository) Join(ctx context.Context, membership domain.Membership) (domain.JoinStatus, error) {
	ret := _mock.Called(ctx, membership)

	if len(ret) == 0 {
		panic("no return value specified for Join")
	}

	var r0 domain.JoinStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Membership) (domain.JoinStatus, error)); ok {
		return returnFunc(ctx, membership)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Membership) domain.JoinStatus); ok {
		r0 = returnFunc(ctx, membership)
	} else {
		r0 = ret.Get(0).(domain.JoinStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Membership) error); ok {
		r1 = returnFunc(ctx, membership)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Join_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Join'
type MockRepository_Join_Call struct {
	*mock.Call
}

// Join is a helper method to define mock.On call
//   - ctx context.Context
//   - membership domain.Membership
func (_e *MockRepository_Expecter) Join(ctx any, membership any) *MockRepository_Join_Call {
	return &MockRepository_Join_Call{Call: _e.mock.On("Join", ctx, membership)}
}

func (_c *MockRepository_Join_Call) Run(run func(ctx context.Context, membership domain.Membership)) *MockRepository_Join_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Membership
		if args[1] != nil {
			arg1 = args[1].(domain.Membership)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Join_Call) Return(joinStatus domain.JoinStatus, err error) *MockRepository_Join_Call {
	_c.Call.Return(joinStatus, err)
	return _c
}

func (_c *MockRepository_Join_Call) RunAndReturn(run func(ctx context.Context, membership domain.Membership) (domain.JoinStatus, error)) *MockRepository_Join_Call {
	_c.Call.Return(run)
	return _c
}

// Leave provides a mock function for the type MockRepository
func (_mock *MockRepository) Leave(ctx context.Context, membership domain.Membership) error {
	ret := _mock.Called(ctx, membership)

	if len(ret) == 0 {
		panic("no return value specified for Leave")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Membership) error); ok {
		r0 = returnFunc(ctx, membership)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Leave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Leave'
type MockRepository_Leave_Call struct {
	*mock.Call
}

// Leave is a helper method to define mock.On call
//   - ctx context.Context
//   - membership domain.Membership
func (_e *MockRepository_Expecter) Leave(ctx any, membership any) *MockRepository_Leave_Call {
	return &MockRepository_Leave_Call{Call: _e.mock.On("Leave", ctx, membership)}
}

func (_c *MockRepository_Leave_Call) Run(run func(ctx context.Context, membership domain.Membership)) *MockRepository_Leave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Membership
		if args[1] != nil {
			arg1 = args[1].(domain.Membership)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Leave_Call) Return(err error) *MockRepository_Leave_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Leave_Call) RunAndReturn(run func(ctx context.Context, membership domain.Membership) error) *MockRepository_Leave_Call {
	_c.Call.Return(run)
	return _c
}

// Members provides a mock function for the type MockRepository
func (_mock *MockRepository) Members(ctx context.Context, roomID domain.RoomID) ([]string, error) {
	ret := _mock.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for Members")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RoomID) ([]string, error)); ok {
		return returnFunc(ctx, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RoomID) []string); ok {
		r0 = returnFunc(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.RoomID) error); ok {
		r1 = returnFunc(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Members_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Members'
type MockRepository_Members_Call struct {
	*mock.Call
}

// Members is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID domain.RoomID
func (_e *MockRepository_Expecter) Members(ctx any, roomID any) *MockRepository_Members_Call {
	return &MockRepository_Members_Call{Call: _e.mock.On("Members", ctx, roomID)}
}

func (_c *MockRepository_Members_Call) Run(run func(ctx context.Context, roomID domain.RoomID)) *MockRepository_Members_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.RoomID
		if args[1] != nil {
			arg1 = args[1].(domain.RoomID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Members_Call) Return(strings []string, err error) *MockRepository_Members_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockRepository_Members_Call) RunAndReturn(run func(ctx context.Context, roomID domain.RoomID) ([]string, error)) *MockRepository_Members_Call {
	_c.Call.Return(run)
	return _c
}
