// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"
	"time"

	"github.com/Dragonqos/lockwood-test/internal/resources/auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// Claim provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Claim(ctx context.Context, userID string, sessionID string) error {
	ret := _mock.Called(ctx, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Claim")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Claim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claim'
type MockSessionRepository_Claim_Call struct {
	*mock.Call
}

// Claim is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - sessionID string
func (_e *MockSessionRepository_Expecter) Claim(ctx any, userID any, sessionID any) *MockSessionRepository_Claim_Call {
	return &MockSessionRepository_Claim_Call{Call: _e.mock.On("Claim", ctx, userID, sessionID)}
}

func (_c *MockSessionRepository_Claim_Call) Run(run func(ctx context.Context, userID string, sessionID string)) *MockSessionRepository_Claim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Claim_Call) Return(err error) *MockSessionRepository_Claim_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Claim_Call) RunAndReturn(run func(ctx context.Context, userID string, sessionID string) error) *MockSessionRepository_Claim_Call {
	_c.Call.Return(run)
	return _c
}

// Current provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Current(ctx context.Context, userID string) (string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Current")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_Current_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Current'
type MockSessionRepository_Current_Call struct {
	*mock.Call
}

// Current is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockSessionRepository_Expecter) Current(ctx any, userID any) *MockSessionRepository_Current_Call {
	return &MockSessionRepository_Current_Call{Call: _e.mock.On("Current", ctx, userID)}
}

func (_c *MockSessionRepository_Current_Call) Run(run func(ctx context.Context, userID string)) *MockSessionRepository_Current_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Current_Call) Return(s string, err error) *MockSessionRepository_Current_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSessionRepository_Current_Call) RunAndReturn(run func(ctx context.Context, userID string) (string, error)) *MockSessionRepository_Current_Call {
	_c.Call.Return(run)
	return _c
}

// Expired provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Expired(ctx context.Context, now time.Time) ([]domain.Session, error) {
	ret := _mock.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for Expired")
	}

	var r0 []domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) ([]domain.Session, error)); ok {
		return returnFunc(ctx, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) []domain.Session); ok {
		r0 = returnFunc(ctx, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_Expired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Expired'
type MockSessionRepository_Expired_Call struct {
	*mock.Call
}

// Expired is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
func (_e *MockSessionRepository_Expecter) Expired(ctx any, now any) *MockSessionRepository_Expired_Call {
	return &MockSessionRepository_Expired_Call{Call: _e.mock.On("Expired", ctx, now)}
}

func (_c *MockSessionRepository_Expired_Call) Run(run func(ctx context.Context, now time.Time)) *MockSessionRepository_Expired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Expired_Call) Return(sessions []domain.Session, err error) *MockSessionRepository_Expired_Call {
	_c.Call.Return(sessions, err)
	return _c
}

func (_c *MockSessionRepository_Expired_Call) RunAndReturn(run func(ctx context.Context, now time.Time) ([]domain.Session, error)) *MockSessionRepository_Expired_Call {
	_c.Call.Return(run)
	return _c
}

// MarkDisconnected provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) MarkDisconnected(ctx context.Context, sessionID string, expiresAt time.Time) error {
	ret := _mock.Called(ctx, sessionID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkDisconnected")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, sessionID, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_MarkDisconnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDisconnected'
type MockSessionRepository_MarkDisconnected_Call struct {
	*mock.Call
}

// MarkDisconnected is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - expiresAt time.Time
func (_e *MockSessionRepository_Expecter) MarkDisconnected(ctx any, sessionID any, expiresAt any) *MockSessionRepository_MarkDisconnected_Call {
	return &MockSessionRepository_MarkDisconnected_Call{Call: _e.mock.On("MarkDisconnected", ctx, sessionID, expiresAt)}
}

func (_c *MockSessionRepository_MarkDisconnected_Call) Run(run func(ctx context.Context, sessionID string, expiresAt time.Time)) *MockSessionRepository_MarkDisconnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_MarkDisconnected_Call) Return(err error) *MockSessionRepository_MarkDisconnected_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_MarkDisconnected_Call) RunAndReturn(run func(ctx context.Context, sessionID string, expiresAt time.Time) error) *MockSessionRepository_MarkDisconnected_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Release(ctx context.Context, userID string, sessionID string) error {
	ret := _mock.Called(ctx, userID, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Release")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockSessionRepository_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - sessionID string
func (_e *MockSessionRepository_Expecter) Release(ctx any, userID any, sessionID any) *MockSessionRepository_Release_Call {
	return &MockSessionRepository_Release_Call{Call: _e.mock.On("Release", ctx, userID, sessionID)}
}

func (_c *MockSessionRepository_Release_Call) Run(run func(ctx context.Context, userID string, sessionID string)) *MockSessionRepository_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Release_Call) Return(err error) *MockSessionRepository_Release_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Release_Call) RunAndReturn(run func(ctx context.Context, userID string, sessionID string) error) *MockSessionRepository_Release_Call {
	_c.Call.Return(run)
	return _c
}

// Touch provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Touch(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Touch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Touch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Touch'
type MockSessionRepository_Touch_Call struct {
	*mock.Call
}

// Touch is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockSessionRepository_Expecter) Touch(ctx any, sessionID any) *MockSessionRepository_Touch_Call {
	return &MockSessionRepository_Touch_Call{Call: _e.mock.On("Touch", ctx, sessionID)}
}

func (_c *MockSessionRepository_Touch_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionRepository_Touch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Touch_Call) Return(err error) *MockSessionRepository_Touch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Touch_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockSessionRepository_Touch_Call {
	_c.Call.Return(run)
	return _c
}

// UserID provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) UserID(ctx context.Context, sessionID string) (string, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for UserID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_UserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserID'
type MockSessionRepository_UserID_Call struct {
	*mock.Call
}

// UserID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockSessionRepository_Expecter) UserID(ctx any, sessionID any) *MockSessionRepository_UserID_Call {
	return &MockSessionRepository_UserID_Call{Call: _e.mock.On("UserID", ctx, sessionID)}
}

func (_c *MockSessionRepository_UserID_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionRepository_UserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_UserID_Call) Return(s string, err error) *MockSessionRepository_UserID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSessionRepository_UserID_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (string, error)) *MockSessionRepository_UserID_Call {
	_c.Call.Return(run)
	return _c
}
