// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package app

import (
	"context"

	"github.com/Dragonqos/lockwood-test/internal/resources/chat/app"
	"github.com/Dragonqos/lockwood-test/internal/resources/chat/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatCoreAPI creates a new instance of MockChatCoreAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatCoreAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatCoreAPI {
	mock := &MockChatCoreAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatCoreAPI is an autogenerated mock type for the ChatCoreAPI type
type MockChatCoreAPI struct {
	mock.Mock
}

type MockChatCoreAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatCoreAPI) EXPECT() *MockChatCoreAPI_Expecter {
	return &MockChatCoreAPI_Expecter{mock: &_m.Mock}
}

// CreateAndJoinRoom provides a mock function for the type MockChatCoreAPI
func (_mock *MockChatCoreAPI) CreateAndJoinRoom(ctx context.Context, command app.CreateAndJoinCommand) error {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for CreateAndJoinRoom")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.CreateAndJoinCommand) error); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatCoreAPI_CreateAndJoinRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAndJoinRoom'
type MockChatCoreAPI_CreateAndJoinRoom_Call struct {
	*mock.Call
}

// CreateAndJoinRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - command app.CreateAndJoinCommand
func (_e *MockChatCoreAPI_Expecter) CreateAndJoinRoom(ctx any, command any) *MockChatCoreAPI_CreateAndJoinRoom_Call {
	return &MockChatCoreAPI_CreateAndJoinRoom_Call{Call: _e.mock.On("CreateAndJoinRoom", ctx, command)}
}

func (_c *MockChatCoreAPI_CreateAndJoinRoom_Call) Run(run func(ctx context.Context, command app.CreateAndJoinCommand)) *MockChatCoreAPI_CreateAndJoinRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.CreateAndJoinCommand
		if args[1] != nil {
			arg1 = args[1].(app.CreateAndJoinCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatCoreAPI_CreateAndJoinRoom_Call) Return(err error) *MockChatCoreAPI_CreateAndJoinRoom_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatCoreAPI_CreateAndJoinRoom_Call) RunAndReturn(run func(ctx context.Context, command app.CreateAndJoinCommand) error) *MockChatCoreAPI_CreateAndJoinRoom_Call {
	_c.Call.Return(run)
	return _c
}

// JoinRoom provides a mock function for the type MockChatCoreAPI
func (_mock *MockChatCoreAPI) JoinRoom(ctx context.Context, command app.JoinCommand) (domain.JoinStatus, error) {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for JoinRoom")
	}

	var r0 domain.JoinStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.JoinCommand) (domain.JoinStatus, error)); ok {
		return returnFunc(ctx, command)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.JoinCommand) domain.JoinStatus); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Get(0).(domain.JoinStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, app.JoinCommand) error); ok {
		r1 = returnFunc(ctx, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatCoreAPI_JoinRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinRoom'
type MockChatCoreAPI_JoinRoom_Call struct {
	*mock.Call
}

// JoinRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - command app.JoinCommand
func (_e *MockChatCoreAPI_Expecter) JoinRoom(ctx any, command any) *MockChatCoreAPI_JoinRoom_Call {
	return &MockChatCoreAPI_JoinRoom_Call{Call: _e.mock.On("JoinRoom", ctx, command)}
}

func (_c *MockChatCoreAPI_JoinRoom_Call) Run(run func(ctx context.Context, command app.JoinCommand)) *MockChatCoreAPI_JoinRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.JoinCommand
		if args[1] != nil {
			arg1 = args[1].(app.JoinCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatCoreAPI_JoinRoom_Call) Return(joinStatus domain.JoinStatus, err error) *MockChatCoreAPI_JoinRoom_Call {
	_c.Call.Return(joinStatus, err)
	return _c
}

func (_c *MockChatCoreAPI_JoinRoom_Call) RunAndReturn(run func(ctx context.Context, command app.JoinCommand) (domain.JoinStatus, error)) *MockChatCoreAPI_JoinRoom_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveRoom provides a mock function for the type MockChatCoreAPI
func (_mock *MockChatCoreAPI) LeaveRoom(ctx context.Context, command app.LeaveCommand) error {
	ret := _mock.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for LeaveRoom")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, app.LeaveCommand) error); ok {
		r0 = returnFunc(ctx, command)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatCoreAPI_LeaveRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveRoom'
type MockChatCoreAPI_LeaveRoom_Call struct {
	*mock.Call
}

// LeaveRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - command app.LeaveCommand
func (_e *MockChatCoreAPI_Expecter) LeaveRoom(ctx any, command any) *MockChatCoreAPI_LeaveRoom_Call {
	return &MockChatCoreAPI_LeaveRoom_Call{Call: _e.mock.On("LeaveRoom", ctx, command)}
}

func (_c *MockChatCoreAPI_LeaveRoom_Call) Run(run func(ctx context.Context, command app.LeaveCommand)) *MockChatCoreAPI_LeaveRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 app.LeaveCommand
		if args[1] != nil {
			arg1 = args[1].(app.LeaveCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatCoreAPI_LeaveRoom_Call) Return(err error) *MockChatCoreAPI_LeaveRoom_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatCoreAPI_LeaveRoom_Call) RunAndReturn(run func(ctx context.Context, command app.LeaveCommand) error) *MockChatCoreAPI_LeaveRoom_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function for the type MockChatCoreAPI
func (_mock *MockChatCoreAPI) ListMembers(ctx context.Context, roomID domain.RoomID) ([]string, error) {
	ret := _mock.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RoomID) ([]string, error)); ok {
		return returnFunc(ctx, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RoomID) []string); ok {
		r0 = returnFunc(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.RoomID) error); ok {
		r1 = returnFunc(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatCoreAPI_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type MockChatCoreAPI_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID domain.RoomID
func (_e *MockChatCoreAPI_Expecter) ListMembers(ctx any, roomID any) *MockChatCoreAPI_ListMembers_Call {
	return &MockChatCoreAPI_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx, roomID)}
}

func (_c *MockChatCoreAPI_ListMembers_Call) Run(run func(ctx context.Context, roomID domain.RoomID)) *MockChatCoreAPI_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.RoomID
		if args[1] != nil {
			arg1 = args[1].(domain.RoomID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatCoreAPI_ListMembers_Call) Return(strings []string, err error) *MockChatCoreAPI_ListMembers_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockChatCoreAPI_ListMembers_Call) RunAndReturn(run func(ctx context.Context, roomID domain.RoomID) ([]string, error)) *MockChatCoreAPI_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// RoomForUser provides a mock function for the type MockChatCoreAPI
func (_mock *MockChatCoreAPI) RoomForUser(ctx context.Context, userID string) (domain.RoomID, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RoomForUser")
	}

	var r0 domain.RoomID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.RoomID, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.RoomID); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.RoomID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatCoreAPI_RoomForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RoomForUser'
type MockChatCoreAPI_RoomForUser_Call struct {
	*mock.Call
}

// RoomForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockChatCoreAPI_Expecter) RoomForUser(ctx any, userID any) *MockChatCoreAPI_RoomForUser_Call {
	return &MockChatCoreAPI_RoomForUser_Call{Call: _e.mock.On("RoomForUser", ctx, userID)}
}

func (_c *MockChatCoreAPI_RoomForUser_Call) Run(run func(ctx context.Context, userID string)) *MockChatCoreAPI_RoomForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatCoreAPI_RoomForUser_Call) Return(roomID domain.RoomID, err error) *MockChatCoreAPI_RoomForUser_Call {
	_c.Call.Return(roomID, err)
	return _c
}

func (_c *MockChatCoreAPI_RoomForUser_Call) RunAndReturn(run func(ctx context.Context, userID string) (domain.RoomID, error)) *MockChatCoreAPI_RoomForUser_Call {
	_c.Call.Return(run)
	return _c
}
